name: Test Pipeline

on:
  push:
    branches: ["main"]

jobs:
  test-website-bucket:
    strategy:
      fail-fast: false
      matrix:
        module:
          - website_bucket
          - route53_zone

    uses: ./.github/workflows/test_terraform_module.yml
    with:
      module-name: ${{ matrix.module }}
