name: Apply Terraform

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

on:
  push:
    branches: [ "main" ]

env:
  tf_version: '1.5.5'
  tg_version: '0.50.6'
    
concurrency: terraform-apply

jobs:
  build:
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        region: ["global", "eu-west-1"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - uses: actions/setup-go@v1
        with:
          go-version: 1.21.0

      - name: Download Go modules
        working-directory: tests
        run: go mod download

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/armakuni-aws-terraform-modules-github-actions
          role-session-name: terratests-for-armakuni-aws-terraform-modules
          aws-region: eu-west-3

      - name: Run tests
        run: just test
