name: Test Terraform Module

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

on:
  workflow_call:
    inputs:
      module-name:
        description: The name of the modules to run the tests for (must match the folder name)
        required: true
        type: string

concurrency: terratest-${{ inputs.module-name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: extractions/setup-just@v1
        
      - uses: actions/setup-go@v1
        with:
          go-version: 1.21.0

      - name: Download Go modules
        run: just deps ${{ inputs.module-name }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/armakuni-aws-terraform-modules-github-actions
          role-session-name: terratests-for-armakuni-aws-terraform-modules
          aws-region: eu-west-3

      - name: Run Terratest (via Go)
        run: just test ${{ inputs.module-name }}

