name: Test Terraform Modules

on:
  push:
    branches: ["main"]

jobs:
  test-module:
    strategy:
      fail-fast: false
      matrix:
        module: []

    uses: ./.github/workflows/test_terraform_module.yml
    with:
      module-name: ${{ matrix.module }}
    secrets: inherit
